### PR TITLE
Added in live autocomplete and theme switching functionality

### PR DESCRIPTION
**Pull request by trumptr**
Added in live autocomplete feature for review. Also added in a theme switcher, which you may like to change the positioning of if you want to keep it, as it tends to wrap when a code history is present in the adjacent dropdown.

### CODE REVIEW

**Comment by IceCreamYou** [comment]
Thanks for contributing!

My preference is to add the theme and autocompletion as persistent options in the extension's settings. Do you mind making that change?

**Comment by trumptr** [comment]
I don't mind working on that - if I'm adding an options page for these settings, are there other settings that you would like included?

**Comment by IceCreamYou** [comment]
Great - there are a few others described in #10 if you feel like throwing them in 😀

**Comment by UziTech** [comment]
I added an options page in my pull request #17 and I added auto complete and a theme option in a separate branch https://github.com/UziTech/Chrome-BigConsole/tree/add-auto-complete

I could add that to my pull request if you would like

**Comment by IceCreamYou** [comment]
@UziTech It would be great if you could add those in a separate PR! If you think Ace needs to be updated for that to work, I think it's worth looking at whether we can pull it in via [ace-builds](https://www.npmjs.com/package/ace-builds) on npm instead of committing all the Ace Editor files to this repo. It's a big package 🙂

**Comment by IceCreamYou** [comment]
This PR is obsoleted by #18. Thanks @UziTech!

**Pull request closed without merging**
